name: Docker Image CD

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-publish:
    strategy:
      matrix:
        include:
          - target: app-prod
            image_name: vrchatauth_app
          - target: celery_worker
            image_name: vrchatauth_celeryworker
          - target: celery_beat
            image_name: vrchatauth_celerybeat
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/eindev/${{ matrix.image_name }}
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        target: ${{ matrix.target }}
        
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - name: 'Deploy'
      id: deploy-dummy
      run: |
        echo "Deploy to $TARGET_ENV triggered"
      env:
        TARGET_ENV: ${{ inputs.env }}
